server:
  context-path: /emall
spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool:
      max-active: 10  #连接池，最大连接数
      max-wait: -1  #连接池：最大阻塞等待时间
      max-idle: 8 #最大空闲连接
      min-idle: 0 #最小空闲连接
    timeout: 0  # 连接超时时间（毫秒）
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/emall?characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 
      #在进行领域映射时,首字母小写，大写字母变为下划线加小写，驼峰命名法——>下划线：UserName => user_name
        #physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  http:
    multipart:
      max-request-size: 10Mb
      max-file-size: 10Mb
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  data:
    elasticsearch:
      cluster-nodes: elasticsearch
      cluster-name: elasticsearch

